export const colors = {
  primary: '#6C63FF',
  primaryLight: '#EEF0FF',
  primaryDark: '#5A52D5',
  secondary: '#FF6584',
  secondaryLight: '#FFF0F3',
  success: '#22C55E',
  successLight: '#F0FDF4',
  danger: '#EF4444',
  dangerLight: '#FEF2F2',
  warning: '#F59E0B',
  warningLight: '#FFFBEB',
  warningBorder: '#FDE68A',
  background: '#F5F5F7',
  card: '#FFFFFF',
  inputBg: '#F3F4F6',
  border: '#E5E7EB',
  text: '#111827',
  textSecondary: '#6B7280',
  muted: '#9CA3AF',
  placeholder: '#9CA3AF',
  white: '#FFFFFF',
  personal: '#6C63FF',
  user: '#22C55E',
  pro: '#7C3AED',
  proLight: '#F5F3FF',
};

export const shadows = {
  sm: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  md: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  lg: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 6,
  },
  colored: (color: string) => ({
    shadowColor: color,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
  }),
};
